"""Real-time departure buffer from MTA GTFS-RT trip-update feeds.

Google Directions plans against the *static* schedule.  When the line a rider is
about to board is actually running late, this module observes that delay (from
the MTA GTFS-RT trip-update feeds) and folds a capped amount into the buffer so
the alarm fires earlier.  It is deliberately conservative — a delay can only move
the leave time *earlier*, never later — and it never claims a precise new
arrival, which would need static trip data we don't carry.

This mirrors :mod:`commutecompass.weather`: an injectable ``fetcher``, a small
``NamedTuple`` result, and a fail-open contract (any error → zero buffer, never a
failed plan).  The hard part is mapping a Directions boarding-stop *name* to a
GTFS ``stop_id``; we do that by fuzzy-matching against the bundled
``data/stops_*.csv`` tables (generated by ``scripts/build_stops.py``).
"""

from __future__ import annotations

import csv
import logging
import time
from datetime import datetime
from importlib import resources
from typing import Any, Callable, NamedTuple, Optional

import httpx
from rapidfuzz import fuzz, process

from commutecompass.config import RealtimeConfig
from commutecompass.gtfs_rt import fetch_feed_message
from commutecompass.models import Route
from commutecompass.retry import retry
from commutecompass.timeutil import NYC_TZ

logger = logging.getLogger(__name__)

__all__ = ["RealtimeDelay", "realtime_delay"]


class RealtimeDelay(NamedTuple):
    minutes: int
    reason: Optional[str]  # e.g. "Q running ~6 min late", or None when on time


_CLEAR = RealtimeDelay(0, None)

# Map a route leg's ``system`` to its bundled stop table.
_STOPS_RESOURCE = {
    "MTA Subway": "stops_subway.csv",
    "LIRR": "stops_lirr.csv",
    "MTA Bus": "stops_bus.csv",
}

# Predicted departures for a system, keyed by feed ``stop_id`` →
# list of (route_id, predicted_departure).
Predictions = dict[str, list[tuple[str, datetime]]]
Fetcher = Callable[[list[str], str], Predictions]

# Reuse a fetched feed set briefly so a multi-event run fetches once per system
# (mirrors poll._alerts_cache).  Only used on the default (non-injected) path.
_FEED_TTL_SECONDS = 60.0
_feed_cache: dict[tuple[str, ...], tuple[float, Predictions]] = {}

# Lazily-loaded, memoized stop tables: system → (names, normalized_name → ids).
_stops_cache: dict[str, tuple[list[str], dict[str, list[str]]]] = {}


def realtime_delay(
    route: Route,
    at_time: datetime,
    config: RealtimeConfig,
    *,
    fetcher: Optional[Fetcher] = None,
) -> RealtimeDelay:
    """Return extra buffer minutes (and a reason) for the boarding line's delay.

    Returns ``RealtimeDelay(0, None)`` when disabled, on any fetch/parse/match
    error, or when service is on time — real-time data is an enhancement, never
    a reason to fail a plan.  ``at_time`` is accepted for symmetry with
    ``weather_buffer``; the scheduled reference actually used is the boarding
    leg's ``depart_at``.  ``fetcher`` is injectable for tests.
    """
    if not config.enabled:
        return _CLEAR
    try:
        return _compute(route, config, fetcher)
    except Exception as exc:  # fail-open: never let real-time break a plan
        logger.debug("realtime delay failed: %s", exc)
        return _CLEAR


def _compute(route: Route, config: RealtimeConfig, fetcher: Optional[Fetcher]) -> RealtimeDelay:
    transit_legs = [leg for leg in route.legs if leg.mode == "TRANSIT"]
    if not transit_legs:
        return _CLEAR

    # Only the first boarding leg is actionable by leaving earlier; downstream
    # delays are unavoidable and belong to the (deferred) reschedule case.
    leg = transit_legs[0]
    system = leg.system
    if system not in _STOPS_RESOURCE or not leg.departure_stop or not leg.line:
        return _CLEAR

    candidate_ids = _match_stop_ids(system, leg.departure_stop, config.fuzzy_threshold)
    if not candidate_ids:
        return _CLEAR

    urls = _feed_urls(system, config)
    if not urls:
        return _CLEAR

    fetch: Fetcher = fetcher or _fetch_predictions
    if fetcher is None:
        preds = _cached_fetch(urls, system, fetch)
    else:
        preds = fetch(urls, system)

    scheduled = leg.depart_at
    window_seconds = config.match_window_minutes * 60

    # Pick the predicted departure closest to the scheduled one — the best
    # estimate of the same train/bus's real-time departure.
    best_abs: Optional[float] = None
    best_diff = 0.0
    for sid in candidate_ids:
        for route_id, dep_dt in preds.get(sid, []):
            if not _route_matches(system, route_id, leg.line):
                continue
            diff = (dep_dt - scheduled).total_seconds()
            if abs(diff) > window_seconds:
                continue
            if best_abs is None or abs(diff) < best_abs:
                best_abs = abs(diff)
                best_diff = diff

    if best_abs is None:
        return _CLEAR

    # Positive diff = running late.  Negative (early/on time) never moves the
    # leave time later, so floor at zero.
    delay_minutes = int(round(max(0.0, best_diff) / 60.0))
    if delay_minutes < config.min_delay_minutes:
        return _CLEAR
    delay_minutes = min(delay_minutes, config.max_buffer_minutes)
    return RealtimeDelay(delay_minutes, f"{leg.line} running ~{delay_minutes} min late")


# ── stop-name → stop_id matching ──────────────────────────────────────────────


def _normalize(name: str) -> str:
    """Lowercase, drop punctuation, collapse whitespace for fuzzy comparison."""
    out: list[str] = []
    prev_space = False
    for ch in name.lower():
        if ch.isalnum():
            out.append(ch)
            prev_space = False
        elif not prev_space:
            out.append(" ")
            prev_space = True
    return "".join(out).strip()


def _load_stops(system: str) -> tuple[list[str], dict[str, list[str]]]:
    cached = _stops_cache.get(system)
    if cached is not None:
        return cached

    resource = _STOPS_RESOURCE[system]
    text = resources.files("commutecompass").joinpath("data", resource).read_text(encoding="utf-8")
    name_to_ids: dict[str, list[str]] = {}
    for row in csv.DictReader(text.splitlines()):
        stop_id = (row.get("stop_id") or "").strip()
        name = _normalize(row.get("stop_name") or "")
        if not stop_id or not name:
            continue
        name_to_ids.setdefault(name, []).append(stop_id)

    result = (list(name_to_ids.keys()), name_to_ids)
    _stops_cache[system] = result
    return result


def _match_stop_ids(system: str, stop_name: str, threshold: int) -> list[str]:
    names, name_to_ids = _load_stops(system)
    if not names:
        return []
    query = _normalize(stop_name)
    if not query:
        return []
    match = process.extractOne(query, names, scorer=fuzz.WRatio, score_cutoff=threshold)
    if match is None:
        return []
    matched_name: str = match[0]
    return _expand_ids(system, name_to_ids.get(matched_name, []))


def _expand_ids(system: str, base_ids: list[str]) -> list[str]:
    """Reconstruct the feed's stop ids from the bundled (parent) ids.

    Subway feeds key stop-time updates on directional platform ids (``R20N`` /
    ``R20S``) whose parent station is ``R20``; we keep the parent in the CSV and
    expand here.  LIRR/bus ids are already flat.
    """
    if system != "MTA Subway":
        return list(base_ids)
    expanded: list[str] = []
    for sid in base_ids:
        expanded.extend((sid, f"{sid}N", f"{sid}S"))
    return expanded


# ── route_id matching (per-system conventions) ───────────────────────────────


def _route_matches(system: str, feed_route_id: str, leg_line: str) -> bool:
    if system == "LIRR":
        # LIRR route_id is a branch number that doesn't map cleanly to the
        # Directions line name — match on stop alone.
        return True
    line = leg_line.upper().strip().replace(" ", "")
    rid = feed_route_id.upper().strip()
    if system == "MTA Bus":
        # OneBusAway route ids look like "MTA NYCT_M15" / "MTABC_Q44".
        if "_" in rid:
            rid = rid.split("_", 1)[1]
        return rid.replace(" ", "") == line
    # Subway: route_id is the line designator; tolerate express suffix ("6X").
    return rid == line or rid.rstrip("X") == line


# ── feed fetching ─────────────────────────────────────────────────────────────


def _feed_urls(system: str, config: RealtimeConfig) -> list[str]:
    if system == "MTA Subway":
        return [u for u in config.subway_tripupdate_urls if u]
    if system == "LIRR":
        return [config.lirr_tripupdate_url] if config.lirr_tripupdate_url else []
    if system == "MTA Bus":
        return [config.bus_tripupdate_url] if config.bus_tripupdate_url else []
    return []


def _normalize_feed_stop(stop_id: str, system: str) -> str:
    if system == "MTA Bus":
        for prefix in ("MTA_", "MTABC_"):
            if stop_id.startswith(prefix):
                return stop_id[len(prefix) :]
    return stop_id


def _fetch_predictions(urls: list[str], system: str) -> Predictions:
    preds: Predictions = {}
    with httpx.Client(timeout=10.0) as client:
        for url in urls:
            if not url:
                continue

            def _do(u: str = url) -> Any:
                return fetch_feed_message(u, system, client)

            try:
                feed = retry(_do, attempts=2, label=f"realtime({system})")
            except Exception as exc:
                logger.debug("realtime feed fetch failed (%s): %s", url, exc)
                continue
            _accumulate(feed, preds, system)
    return preds


def _accumulate(feed: Any, preds: Predictions, system: str) -> None:
    for entity in feed.entity:
        if not entity.HasField("trip_update"):
            continue
        tu = entity.trip_update
        route_id = tu.trip.route_id
        for stu in tu.stop_time_update:
            stop_id = stu.stop_id
            if not stop_id:
                continue
            ts = 0
            if stu.HasField("departure") and stu.departure.time:
                ts = stu.departure.time
            elif stu.HasField("arrival") and stu.arrival.time:
                ts = stu.arrival.time
            if not ts:
                continue
            key = _normalize_feed_stop(stop_id, system)
            preds.setdefault(key, []).append(
                (route_id, datetime.fromtimestamp(ts, tz=NYC_TZ))
            )


def _cached_fetch(urls: list[str], system: str, fetcher: Fetcher) -> Predictions:
    key = tuple(urls)
    now = time.monotonic()
    hit = _feed_cache.get(key)
    if hit is not None and now - hit[0] < _FEED_TTL_SECONDS:
        return hit[1]
    preds = fetcher(urls, system)
    _feed_cache[key] = (now, preds)
    return preds
